// export const CAROUSEL_IMAGES = [
// 	{
// 		id: '1',
// 		src: '/images/slides/img01.jpg',
// 		alt: 'Image 1',
// 		// title: 'Image 1 Title',
// 		// description: 'Image 1 Description',
// 		// buttonText: 'Button Text 1',
// 	},
// 	{
// 		id: '2',
// 		src: '/images/slides/img02.jpg',
// 		alt: 'Image 2',
// 		// title: 'Image 2 Title',
// 		// description: 'Image 2 Description',
// 		// buttonText: 'Button Text 2',
// 	},
// 	{
// 		id: '3',
// 		src: '/images/slides/img03.jpg',
// 		alt: 'Image 3',
// 		// title: 'Image 3 Title',
// 		// description: 'Image 3 Description',
// 		// buttonText: 'Button Text 3',
// 	},
// 	{
// 		id: '4',
// 		src: '/images/slides/img04.jpg',
// 		alt: 'Image 4',
// 		// title: 'Image 3 Title',
// 		// description: 'Image 3 Description',
// 		// buttonText: 'Button Text 3',
// 	},
// 	{
// 		id: '5',
// 		src: '/images/slides/img05.jpg',
// 		alt: 'Image 5',
// 		// title: 'Image 3 Title',
// 		// description: 'Image 3 Description',
// 		// buttonText: 'Button Text 3',
// 	},
// ];

export const CAROUSEL_IMAGES = [
	{
		id: '1',
		src: '/images/slides/1.webp',
		alt: 'Image 1',
		// title: 'Image 1 Title',
		// description: 'Image 1 Description',
		// buttonText: 'Button Text 1',
	},
	{
		id: '2',
		src: '/images/slides/2.webp',
		alt: 'Image 2',
		// title: 'Image 2 Title',
		// description: 'Image 2 Description',
		// buttonText: 'Button Text 2',
	},
	{
		id: '3',
		src: '/images/slides/3.webp',
		alt: 'Image 3',
		// title: 'Image 3 Title',
		// description: 'Image 3 Description',
		// buttonText: 'Button Text 3',
	},
	{
		id: '4',
		src: '/images/slides/4.webp',
		alt: 'Image 4',
		// title: 'Image 4 Title',
		// description: 'Image 4 Description',
		// buttonText: 'Button Text 4',
	},
	{
		id: '5',
		src: '/images/slides/5.webp',
		alt: 'Image 5',
		// title: 'Image 5 Title',
		// description: 'Image 5 Description',
		// buttonText: 'Button Text 5',
	},
	{
		id: '6',
		src: '/images/slides/6.webp',
		alt: 'Image 6',
		// title: 'Image 6 Title',
		// description: 'Image 6 Description',
		// buttonText: 'Button Text 6',
	},
	{
		id: '7',
		src: '/images/slides/7.webp',
		alt: 'Image 7',
		// title: 'Image 7 Title',
		// description: 'Image 7 Description',
		// buttonText: 'Button Text 7',
	},
	{
		id: '8',
		src: '/images/slides/8.webp',
		alt: 'Image 8',
		// title: 'Image 8 Title',
		// description: 'Image 8 Description',
		// buttonText: 'Button Text 8',
	},
];

export const LATEST_PRODUCTS = [
	{
		id: '1',
		image: '/images/device/fc01.jpg',
		header: 'Car Charger',
		// footer: <div>This is the footer 1</div>,
		// description: 'This is a card 1',
	},
	{
		id: '2',
		image: '/images/device/fe2.jpg',
		header: 'Ear Peice',
		// footer: <div>This is the footer 2</div>,
		// description: 'This is a card 2',
	},
	{
		id: '3',
		image: '/images/device/fs01.jpg',
		header: 'Charger Adapter',
		// footer: <div>This is the footer 3</div>,
		// description: 'This is a card 3',
	},
	{
		id: '4',
		image: '/images/device/fl404.jpg',
		header: 'Fast Charger',
		// footer: <div>This is the footer 4</div>,
		// description: 'This is a card 4',
	},
	{
		id: '5',
		image: '/images/device/fl218.jpg',
		header: 'Dual Input Charger',
		// footer: <div>This is the footer 5</div>,
		// description: 'This is a card 5',
	},
];
