import Homepage from '@/components/home-page';
import Footer from '@/components/layout/footer';
import Navbar from '@/components/layout/navigation-bar';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Flick Electronics</title>
				<meta
					name='description'
					content='Generated by ISCE Digital Concept'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/logo.png'
				/>
			</Head>
			<Navbar />
			<main>
				<Homepage />
			</main>
			<Footer />
		</>
	);
}
